### Series 만들기

In [1]:
import pandas as pd

In [2]:
ls1 = [1,2,3,4,5,6,7,8,9]
ls2 = [1,2,3,'Apple','Banana','Cherry',7,8,9]

sr1 = pd.Series(ls1)
sr2 = pd.Series(ls2)

sr2

0         1
1         2
2         3
3     Apple
4    Banana
5    Cherry
6         7
7         8
8         9
dtype: object

In [3]:
sr1.name = 'Numbers'
sr2.name = 'Word'

sr2

0         1
1         2
2         3
3     Apple
4    Banana
5    Cherry
6         7
7         8
8         9
Name: Word, dtype: object

In [4]:
dic1 = {'A':1, 'B':2, 'C':3, 'D':4, 'E':5}

sr3 = pd.Series(dic1)
sr3.name = 'Alphabets'
sr3

A    1
B    2
C    3
D    4
E    5
Name: Alphabets, dtype: int64

### CSV 파일을 Series로 불러오기

In [5]:
samsung_price = pd.read_csv("Data/삼성전자 종가.csv", index_col=0, header = 0).squeeze("columns")
samsung_price

Date
2018-01-02    51020
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...  
2021-12-13    76800
2021-12-14    77000
2021-12-15    77600
2021-12-16    77800
2021-12-17    78000
Name: Close, Length: 977, dtype: int64

### Series Index&Value

In [6]:
samsung_price = pd.read_csv("Data/삼성전자 종가.csv", index_col=0, header = 0).squeeze("columns")
samsung_price.index

Index(['2018-01-02', '2018-01-03', '2018-01-04', '2018-01-05', '2018-01-08',
       '2018-01-09', '2018-01-10', '2018-01-11', '2018-01-12', '2018-01-15',
       ...
       '2021-12-06', '2021-12-07', '2021-12-08', '2021-12-09', '2021-12-10',
       '2021-12-13', '2021-12-14', '2021-12-15', '2021-12-16', '2021-12-17'],
      dtype='object', name='Date', length=977)

In [7]:
# 만약 삼성전자 Series에 2020-12-15 Data가 있을까?
date = '2020-12-15'

if date in samsung_price.index:
    print(samsung_price.loc[date])
else:
    print('No data')

73800


In [8]:
# 만약 삼성전자 Series에 100번째 Data값은 무엇일까?
samsung_price.iloc[100]

np.int64(49500)

### Series에 새로운 값을 추가하고 싶다면?

In [9]:
# 삼성전자 Series의 총 길이는?
samsung_price = pd.read_csv("Data/삼성전자 종가.csv", index_col=0, header = 0).squeeze("columns")
samsung_price.shape

(977,)

In [10]:
# 삼성전자 Series에 '2021-12-20'가격을 업데이트 하고 싶다면?
samsung_price.loc["2021-12-20"] = 77100
samsung_price

Date
2018-01-02    51020
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...  
2021-12-14    77000
2021-12-15    77600
2021-12-16    77800
2021-12-17    78000
2021-12-20    77100
Name: Close, Length: 978, dtype: int64

### 두 개의 Series 연결하기

In [11]:
# samsung_excel 파일의 sheet1(2018~2019)와 sheet2(2020~2021)를 연결!
series1_samsung = pd.read_excel('Data/samsung_excel.xlsx', sheet_name = 'Sheet1', index_col=0).squeeze("columns")
series2_samsung = pd.read_excel('Data/samsung_excel.xlsx', sheet_name = 'Sheet2', index_col=0).squeeze("columns")

series_samsung = pd.concat([series1_samsung, series2_samsung], ignore_index=False)
series_samsung

Date
2018-01-02    51020
2018-01-03    51620
2018-01-04    51080
2018-01-05    52120
2018-01-08    52020
              ...  
2021-12-20    77100
2021-12-21    78100
2021-12-22    79400
2021-12-23    79900
2021-12-24    80500
Name: Close, Length: 982, dtype: int64

### Series 기본 통계치 구하기

In [12]:
# 삼성전자 Series에 가장 큰 값은?
samsung_price = pd.read_csv('Data/삼성전자 종가.csv', index_col=0, header=0).squeeze("columns")
samsung_price.max()
samsung_price.describe()

count      977.000000
mean     57295.854657
std      14084.402274
min      37450.000000
25%      46300.000000
50%      51300.000000
75%      70200.000000
max      91000.000000
Name: Close, dtype: float64

In [13]:
# 삼성전자 Series에 가장 큰 값의 날짜는?
samsung_price.index[samsung_price.values == samsung_price.max()]
samsung_price.index[samsung_price.argmax()]

'2021-01-11'

### About Numpy 1: Array - Series와 DataFrame에서 다영ㄴ하게 생각했던 연산의 이유

In [14]:
import numpy as np

ls = [1, 2, 3, 4]
ls

[1, 2, 3, 4]

In [15]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.shape)

[1 2 3 4]
(4,)


### About Numpy 2: Broadcasting - Series와 DataFrame에서 다양하게 생각했던 연산의 이유

In [16]:
arr1 = np.array([[1, 2], [2, 5]])
arr1 + 1

array([[2, 3],
       [3, 6]])

In [17]:
arr1 * 10

array([[10, 20],
       [20, 50]])

### Series 연산

In [18]:
# 2018년부터 현재까지 삼성전자 수익률중 가장 크게 올랐을때, 얼마나 올랐을까?
samsung_price = pd.read_csv('Data/삼성전자 종가.csv', index_col=0, header=0).squeeze("columns")
samsung_return = (samsung_price - samsung_price.shift(1))/samsung_price.shift(1)
samsung_return

Date
2018-01-02         NaN
2018-01-03    0.011760
2018-01-04   -0.010461
2018-01-05    0.020360
2018-01-08   -0.001919
                ...   
2021-12-13   -0.001300
2021-12-14    0.002604
2021-12-15    0.007792
2021-12-16    0.002577
2021-12-17    0.002571
Name: Close, Length: 977, dtype: float64

In [19]:
samsung_price.pct_change()

Date
2018-01-02         NaN
2018-01-03    0.011760
2018-01-04   -0.010461
2018-01-05    0.020360
2018-01-08   -0.001919
                ...   
2021-12-13   -0.001300
2021-12-14    0.002604
2021-12-15    0.007792
2021-12-16    0.002577
2021-12-17    0.002571
Name: Close, Length: 977, dtype: float64

In [20]:
samsung_return.max()

np.float64(0.10470588235294118)

In [21]:
samsung_return.index[samsung_return.argmax()]

'2020-03-24'

### NaN값 처리

In [22]:
samsung_price = pd.read_csv('Data/삼성전자 종가.csv', index_col=0, header=0).squeeze("columns")
samsung_return = (samsung_price - samsung_price.shift(1))/samsung_price.shift(1)
samsung_return

Date
2018-01-02         NaN
2018-01-03    0.011760
2018-01-04   -0.010461
2018-01-05    0.020360
2018-01-08   -0.001919
                ...   
2021-12-13   -0.001300
2021-12-14    0.002604
2021-12-15    0.007792
2021-12-16    0.002577
2021-12-17    0.002571
Name: Close, Length: 977, dtype: float64

In [23]:
samsung_return.dropna()

Date
2018-01-03    0.011760
2018-01-04   -0.010461
2018-01-05    0.020360
2018-01-08   -0.001919
2018-01-09   -0.031142
                ...   
2021-12-13   -0.001300
2021-12-14    0.002604
2021-12-15    0.007792
2021-12-16    0.002577
2021-12-17    0.002571
Name: Close, Length: 976, dtype: float64

In [24]:
samsung_return.fillna(0)

Date
2018-01-02    0.000000
2018-01-03    0.011760
2018-01-04   -0.010461
2018-01-05    0.020360
2018-01-08   -0.001919
                ...   
2021-12-13   -0.001300
2021-12-14    0.002604
2021-12-15    0.007792
2021-12-16    0.002577
2021-12-17    0.002571
Name: Close, Length: 977, dtype: float64

### Series 순서대로 나열하기

In [25]:
# 삼성전자 Series를 가격이 큰 순서대로 나타내보자. 그럼 어떤 시기에 가격이 가장 높았을까?
samsung_price = pd.read_csv('Data/삼성전자 종가.csv', index_col=0, header=0).squeeze("columns")
samsung_return = (samsung_price - samsung_price.shift(1))/samsung_price.shift(1)

In [26]:
samsung_price.sort_index(ascending=False)

Date
2021-12-17    78000
2021-12-16    77800
2021-12-15    77600
2021-12-14    77000
2021-12-13    76800
              ...  
2018-01-08    52020
2018-01-05    52120
2018-01-04    51080
2018-01-03    51620
2018-01-02    51020
Name: Close, Length: 977, dtype: int64

In [27]:
samsung_price.sort_values(ascending=False).head(30)

Date
2021-01-11    91000
2021-01-12    90600
2021-01-14    89700
2021-01-13    89700
2021-01-25    89400
2021-01-08    88800
2021-01-21    88100
2021-01-15    88000
2021-01-20    87200
2021-01-19    87000
2021-01-22    86800
2021-01-26    86700
2021-04-06    86000
2021-01-27    85600
2021-04-07    85600
2021-04-05    85400
2021-02-25    85300
2021-01-18    85000
2021-02-16    84900
2021-04-02    84800
2021-04-08    84700
2021-02-03    84600
2021-02-02    84400
2021-02-15    84200
2021-04-15    84100
2021-04-13    84000
2021-04-14    84000
2021-03-03    84000
2021-04-16    83900
2021-04-20    83900
Name: Close, dtype: int64

### Series 특정 조건에 맞는 값을 찾고 싶을 때

In [28]:
# 삼성전자 Series에서 수익률이 4%이상일때의 빈도수는 어느정도 였을까?
samsung_price = pd.read_csv('Data/삼성전자 종가.csv', index_col=0, header=0).squeeze("columns")
samsung_return = (samsung_price - samsung_price.shift(1))/samsung_price.shift(1)
samsung_return *= 100
sum(samsung_return.values >= 4) / len(samsung_return) * 100

np.float64(1.7400204708290685)

In [29]:
# 삼성전자 Series에서 수익률이 4%이상일때 1로, 아닐때 0으로 하는 새로운 Series를 만들어보자.
samsung_return_over_4 = pd.Series(np.where(samsung_return.values >= 4, 1, 0), index=samsung_return.index)
samsung_return_over_4

Date
2018-01-02    0
2018-01-03    0
2018-01-04    0
2018-01-05    0
2018-01-08    0
             ..
2021-12-13    0
2021-12-14    0
2021-12-15    0
2021-12-16    0
2021-12-17    0
Length: 977, dtype: int64

### Series Rolling

In [30]:
# 삼성전자 Series에서 30일 이동평균을 구해보자.
samsung_price = pd.read_csv('Data/삼성전자 종가.csv', index_col=0, header=0).squeeze("columns")
samsung_price.rolling(window=30).mean()

Date
2018-01-02             NaN
2018-01-03             NaN
2018-01-04             NaN
2018-01-05             NaN
2018-01-08             NaN
                  ...     
2021-12-13    73090.000000
2021-12-14    73273.333333
2021-12-15    73513.333333
2021-12-16    73753.333333
2021-12-17    74013.333333
Name: Close, Length: 977, dtype: float64

### Series 구간 나누기

In [31]:
# 삼성전자 Series의 수익률 구간을 구해보자(10등분)
samsung_return = (samsung_price - samsung_price.shift(1))/samsung_price.shift(1) * 100
pd.cut(samsung_return, bins=10).value_counts()

Close
(-1.33, 0.356]      414
(0.356, 2.041]      298
(-3.016, -1.33]     137
(2.041, 3.727]       70
(-4.702, -3.016]     31
(3.727, 5.413]       19
(-6.405, -4.702]      3
(5.413, 7.099]        2
(7.099, 8.785]        1
(8.785, 10.471]       1
Name: count, dtype: int64

In [32]:
pd.qcut(samsung_return, q=10).value_counts()

Close
(-0.332, 0.0]       108
(-6.389, -1.938]     98
(-1.938, -1.161]     98
(-0.702, -0.332]     98
(0.753, 1.22]        98
(2.003, 10.471]      98
(-1.161, -0.702]     97
(0.358, 0.753]       97
(1.22, 2.003]        97
(0.0, 0.358]         87
Name: count, dtype: int64

### 서로 다른 길이의 두 개의 Series 연산

In [33]:
# 삼성전자 Series와 Kospi의 상관관계를 구해보자.
samsung_price = pd.read_csv('Data/삼성전자 종가.csv', index_col=0, header=0).squeeze("columns")
kospi = pd.read_csv('Data/KOSPI.csv', index_col=0, header=0).squeeze("columns")
print(samsung_price.shape)
print(kospi.shape)

(977,)
(477,)


In [34]:
samsung_price = samsung_price.loc['2020-01-02':]
samsung_price.shape

(487,)

In [36]:
samsung_re = samsung_price.loc[kospi.index]
samsung_re.shape

(477,)

In [37]:
samsung_re.corr(kospi)

np.float64(0.9583971132808289)

In [38]:
samsung_price.corr(kospi)

np.float64(0.9583971132808289)

In [41]:
np.corrcoef(samsung_re, kospi)
# np.corrcoef(samsung_price, kospi)

array([[1.        , 0.95839711],
       [0.95839711, 1.        ]])

In [43]:
kospi.loc['2021-12-18'] = 2986.45
kospi.tail()

Date
2021-12-14    2987.95
2021-12-15    2989.39
2021-12-16    3006.41
2021-12-17    3017.73
2021-12-18    2986.45
Name: Close, dtype: float64

In [44]:
expanded_index = samsung_price.index.union(kospi.index)
samsung_price_expanded = samsung_price.reindex(expanded_index)
kospi_expanded = kospi.reindex(expanded_index)
samsung_price_expanded.corr(kospi_expanded)

np.float64(0.9583971132808289)

### Series 마무리